import { Student, Project, Memory } from './types';

export const STUDENTS: Student[] = [
  { id: '1', name: 'ABHILASH K K', techStack: ['96% Attendance', 'React', 'Node.js'], image: 'https://picsum.photos/seed/1/400/400' },
  { id: '2', name: 'ABHINAND K K', techStack: ['95% Attendance', 'Python', 'Django'], image: 'https://picsum.photos/seed/2/400/400' },
  { id: '3', name: 'ABHINAND M A', techStack: ['93% Attendance', 'Flutter', 'Firebase'], image: 'https://picsum.photos/seed/3/400/400' },
  { id: '4', name: 'ABHINANTH S PILLAI', techStack: ['94% Attendance', 'Java', 'Spring'], image: 'https://picsum.photos/seed/4/400/400' },
  { id: '5', name: 'ADONIA CYRUS', techStack: ['95% Attendance', 'UI/UX', 'Figma'], image: 'https://picsum.photos/seed/5/400/400' },
  { id: '6', name: 'AKASH A', techStack: ['97% Attendance', 'Go', 'Kubernetes'], image: 'https://picsum.photos/seed/6/400/400' },
  { id: '7', name: 'AKSHAI RAJ', techStack: ['100% Attendance', 'Machine Learning'], image: 'https://picsum.photos/seed/7/400/400' },
  { id: '8', name: 'ALBIN SURESH', techStack: ['100% Attendance', 'Cybersecurity'], image: 'https://picsum.photos/seed/8/400/400' },
  { id: '9', name: 'ALEENA ROBY', techStack: ['97% Attendance', 'Data Science'], image: 'https://picsum.photos/seed/9/400/400' },
  { id: '10', name: 'ALFIYA ISMAIL', techStack: ['95% Attendance', 'Web Dev'], image: 'https://picsum.photos/seed/10/400/400' },
  { id: '11', name: 'ALKA MARIA JISS', techStack: ['99% Attendance', 'Cloud Computing'], image: 'https://picsum.photos/seed/11/400/400' },
  { id: '12', name: 'AMAL S KUMAR', techStack: ['91% Attendance', 'DevOps'], image: 'https://picsum.photos/seed/12/400/400' },
  { id: '13', name: 'ANAND S BOSCO', techStack: ['78% Attendance', 'Mobile Apps'], image: 'https://picsum.photos/seed/13/400/400' },
  { id: '14', name: 'ANANDHU PRADEEP', techStack: ['99% Attendance', 'Backend Dev'], image: 'https://picsum.photos/seed/14/400/400' },
  { id: '15', name: 'ANGEL RENOY', techStack: ['99% Attendance', 'Frontend Dev'], image: 'https://picsum.photos/seed/15/400/400' },
  { id: '16', name: 'ANGELIN RAPHY', techStack: ['97% Attendance', 'Full Stack'], image: 'https://picsum.photos/seed/16/400/400' },
  { id: '17', name: 'ANJALI SUNIL', techStack: ['78% Attendance', 'Software Engineering'], image: 'https://picsum.photos/seed/17/400/400' },
  { id: '18', name: 'ANJALY V S', techStack: ['95% Attendance', 'Database Mgmt'], image: 'https://picsum.photos/seed/18/400/400' },
  { id: '19', name: 'ARUN BIJU THOMAS', techStack: ['96% Attendance', 'Embedded Systems'], image: 'https://picsum.photos/seed/19/400/400' },
  { id: '20', name: 'ARUN PAPPACHAN', techStack: ['78% Attendance', 'Networking'], image: 'https://picsum.photos/seed/20/400/400' },
  { id: '21', name: 'ATHULYA R MOHAN', techStack: ['96% Attendance', 'AI/ML'], image: 'https://picsum.photos/seed/21/400/400' },
  { id: '22', name: 'BIYA JOMON', techStack: ['99% Attendance', 'Cloud Arch'], image: 'https://picsum.photos/seed/22/400/400' },
  { id: '23', name: 'BLESSON JOSEPH BYJU', techStack: ['91% Attendance', 'Game Dev'], image: 'https://picsum.photos/seed/23/400/400' },
  { id: '24', name: 'DARIL TOM JOSE', techStack: ['100% Attendance', 'Blockchain'], image: 'https://picsum.photos/seed/24/400/400' },
  { id: '25', name: 'DIYA SEBASTIAN', techStack: ['90% Attendance', 'AR/VR'], image: 'https://picsum.photos/seed/25/400/400' },
  { id: '26', name: 'EDSON EDWIN NINAN', techStack: ['93% Attendance', 'IoT'], image: 'https://picsum.photos/seed/26/400/400' },
  { id: '27', name: 'ELIZEBETH MATHEW', techStack: ['97% Attendance', 'Big Data'], image: 'https://picsum.photos/seed/27/400/400' },
  { id: '28', name: 'FATHIMA IRFANA', techStack: ['97% Attendance', 'Digital Marketing'], image: 'https://picsum.photos/seed/28/400/400' },
  { id: '29', name: 'FEBA BIJU', techStack: ['97% Attendance', 'Quality Assurance'], image: 'https://picsum.photos/seed/29/400/400' },
  { id: '30', name: 'GAYATHRI M', techStack: ['95% Attendance', 'Project Mgmt'], image: 'https://picsum.photos/seed/30/400/400' },
  { id: '31', name: 'GOUTHAM SREEKUMAR', techStack: ['100% Attendance', 'Ethical Hacking'], image: 'https://picsum.photos/seed/31/400/400' },
  { id: '32', name: 'HAINES JOSE PAULSON', techStack: ['100% Attendance', 'System Design'], image: 'https://picsum.photos/seed/32/400/400' },
  { id: '33', name: 'HEINS DEVASIA', techStack: ['97% Attendance', 'Microservices'], image: 'https://picsum.photos/seed/33/400/400' },
  { id: '34', name: 'JAGANATH SYAM', techStack: ['88% Attendance', 'Rust', 'WebAssembly'], image: 'https://picsum.photos/seed/34/400/400' },
  { id: '35', name: 'JESTIN SHAJI', techStack: ['96% Attendance', 'Next.js', 'Tailwind'], image: 'https://picsum.photos/seed/35/400/400' },
  { id: '36', name: 'JIBIN P CHACKO', techStack: ['94% Attendance', 'Kotlin', 'Android'], image: 'https://picsum.photos/seed/36/400/400' },
  { id: '37', name: 'JIDHIN MATHEW', techStack: ['87% Attendance', 'Swift', 'iOS'], image: 'https://picsum.photos/seed/37/400/400' },
  { id: '38', name: 'JIYA THOMAS', techStack: ['94% Attendance', 'Vue.js', 'Nuxt'], image: 'https://picsum.photos/seed/38/400/400' },
  { id: '39', name: 'JOBIN JAMES', techStack: ['99% Attendance', 'GraphQL', 'Apollo'], image: 'https://picsum.photos/seed/39/400/400' },
  { id: '40', name: 'JOSEKUTTY SHOBY', techStack: ['88% Attendance', 'C++', 'Algorithms'], image: 'https://picsum.photos/seed/40/400/400' },
  { id: '41', name: 'JOSEPH MATHEW', techStack: ['86% Attendance', 'PHP', 'Laravel'], image: 'https://picsum.photos/seed/41/400/400' },
  { id: '42', name: 'KEERTHANA M', techStack: ['94% Attendance', 'Ruby on Rails'], image: 'https://picsum.photos/seed/42/400/400' },
  { id: '43', name: 'KRISHNA DEEPESH', techStack: ['87% Attendance', 'Svelte', 'Vite'], image: 'https://picsum.photos/seed/43/400/400' },
  { id: '44', name: 'LAMEES JALEEL', techStack: ['92% Attendance', 'Angular', 'RxJS'], image: 'https://picsum.photos/seed/44/400/400' },
  { id: '45', name: 'LIYA MARY BIJU', techStack: ['92% Attendance', 'Express', 'MongoDB'], image: 'https://picsum.photos/seed/45/400/400' },
  { id: '46', name: 'MAHI MANOJ M', techStack: ['84% Attendance', 'TensorFlow', 'Keras'], image: 'https://picsum.photos/seed/46/400/400' },
  { id: '47', name: 'MILAN M ANTONY', techStack: ['89% Attendance', 'PyTorch', 'NLP'], image: 'https://picsum.photos/seed/47/400/400' },
  { id: '48', name: 'MUHAMMED JASIR P P', techStack: ['93% Attendance', 'Computer Vision'], image: 'https://picsum.photos/seed/48/400/400' },
  { id: '49', name: 'NAVEENA ELSA KOSHY', techStack: ['98% Attendance', 'Product Design'], image: 'https://picsum.photos/seed/49/400/400' },
  { id: '50', name: 'NEHU SAM ABRAHAM', techStack: ['97% Attendance', 'Interaction Design'], image: 'https://picsum.photos/seed/50/400/400' },
  { id: '51', name: 'PRINCE ABRAHAM SHAJI', techStack: ['96% Attendance', 'Business Analysis'], image: 'https://picsum.photos/seed/51/400/400' },
  { id: '52', name: 'RICH TOJI', techStack: ['92% Attendance', 'Technical Writing'], image: 'https://picsum.photos/seed/52/400/400' },
  { id: '53', name: 'RINTA THOMAS', techStack: ['97% Attendance', 'SEO', 'Analytics'], image: 'https://picsum.photos/seed/53/400/400' },
  { id: '54', name: 'SAINU ANNA SAJAN', techStack: ['95% Attendance', 'E-commerce'], image: 'https://picsum.photos/seed/54/400/400' },
  { id: '55', name: 'SIDHARTH S UPPODAN', techStack: ['79% Attendance', 'Game Design'], image: 'https://picsum.photos/seed/55/400/400' },
  { id: '56', name: 'SNEHA M S', techStack: ['97% Attendance', 'Branding'], image: 'https://picsum.photos/seed/56/400/400' },
  { id: '57', name: 'SUBIN JOSEPH VARGHESE', techStack: ['94% Attendance', 'IT Support'], image: 'https://picsum.photos/seed/57/400/400' },
  { id: '58', name: 'THEERDHA RAJU', techStack: ['89% Attendance', 'Database Admin'], image: 'https://picsum.photos/seed/58/400/400' },
  { id: '59', name: 'VISMAYA KOORMA', techStack: ['88% Attendance', 'Network Admin'], image: 'https://picsum.photos/seed/59/400/400' },
  { id: '60', name: 'VIVEK JOSEPH VATTAVAYALIL', techStack: ['82% Attendance', 'Security Audit'], image: 'https://picsum.photos/seed/60/400/400' }
];

export const PROJECTS: Project[] = [
  {
    id: '1',
    title: 'Nexus AI',
    description: 'A collaborative AI platform for real-time code generation and pair programming.',
    techStack: ['Next.js', 'OpenAI', 'Socket.io'],
    author: 'Alex Rivera',
    image: 'https://picsum.photos/seed/nexus/800/450'
  },
  {
    id: '2',
    title: 'EcoTrack',
    description: 'IoT based solution for monitoring and reducing carbon footprint in smart cities.',
    techStack: ['React Native', 'Node.js', 'IoT'],
    author: 'Sarah Chen',
    image: 'https://picsum.photos/seed/eco/800/450'
  },
  {
    id: '3',
    title: 'CryptoVault',
    description: 'Secure decentralized wallet with multi-signature support and hardware integration.',
    techStack: ['Solidity', 'Web3.js', 'React'],
    author: 'Liam Wilson',
    image: 'https://picsum.photos/seed/crypto/800/450'
  }
];

export const MEMORIES: Memory[] = [
  { id: '1', url: 'https://picsum.photos/seed/mem1/600/800', caption: 'First Day at Campus', type: 'image' },
  { id: '2', url: 'https://picsum.photos/seed/mem2/800/600', caption: 'Hackathon 2025', type: 'image' },
  { id: '3', url: 'https://picsum.photos/seed/mem3/600/600', caption: 'Coffee Breaks', type: 'image' },
  { id: '4', url: 'https://picsum.photos/seed/mem4/700/900', caption: 'Project Submissions', type: 'image' },
  { id: '5', url: 'https://picsum.photos/seed/mem5/900/700', caption: 'Batch Trip', type: 'image' },
  { id: '6', url: 'https://picsum.photos/seed/mem6/600/800', caption: 'Late Night Coding', type: 'image' }
];
